/*
 *  keyboard.ts
 *  Nifty HTML5 Game Engine
 *  Keyboard Input Manager
 */

module Nifty {
    export class Keyboard {
        private static keyCodeLookupTable = {
              8: Key.BackSpace,
              9: Key.Tab,
             13: Key.Return,
             16: Key.Shift,
             17: Key.Control,
             18: Key.Alt,
             19: Key.Pause,
             20: Key.CapsLock,
             27: Key.Escape,
             32: Key.Space,
             33: Key.PageUp,
             34: Key.PageDown,
             35: Key.End,
             36: Key.Home,
             37: Key.Left,
             38: Key.Up,
             39: Key.Right,
             40: Key.Down,
             45: Key.Insert,
             46: Key.Delete,
             48: Key.Num0,
             49: Key.Num1,
             50: Key.Num2,
             51: Key.Num3,
             52: Key.Num4,
             53: Key.Num5,
             54: Key.Num6,
             55: Key.Num7,
             56: Key.Num8,
             57: Key.Num9,
             65: Key.A,
             66: Key.B,
             67: Key.C,
             68: Key.D,
             69: Key.E,
             70: Key.F,
             71: Key.G,
             72: Key.H,
             73: Key.I,
             74: Key.J,
             75: Key.K,
             76: Key.L,
             77: Key.M,
             78: Key.N,
             79: Key.O,
             80: Key.P,
             81: Key.Q,
             82: Key.R,
             83: Key.S,
             84: Key.T,
             85: Key.U,
             86: Key.V,
             87: Key.W,
             88: Key.X,
             89: Key.Y,
             90: Key.Z,
             91: Key.LSystem,
             92: Key.RSystem,
             96: Key.Numpad0,
             97: Key.Numpad1,
             98: Key.Numpad2,
             99: Key.Numpad3,
            100: Key.Numpad4,
            101: Key.Numpad5,
            102: Key.Numpad6,
            103: Key.Numpad7,
            104: Key.Numpad8,
            105: Key.Numpad9,
            106: Key.Multiply,
            107: Key.Add,
            109: Key.Subtract,
            110: Key.Period,
            111: Key.Divide,
            112: Key.F1,
            113: Key.F2,
            114: Key.F3,
            115: Key.F4,
            116: Key.F5,
            117: Key.F6,
            118: Key.F7,
            119: Key.F8,
            120: Key.F9,
            121: Key.F10,
            122: Key.F11,
            123: Key.F12,
            144: Key.NumLock,
            145: Key.ScrollLock,
            186: Key.SemiColon,
            187: Key.Equal,
            188: Key.Comma,
            189: Key.Dash,
            190: Key.Period,
            191: Key.Slash,
            192: Key.Grave,
            219: Key.LBracket,
            220: Key.BackSlash,
            221: Key.RBracket,
            222: Key.Quote
        };
        
        private static keyState: { [key: number]: boolean; } = {};
        
        public static isKeyPressed(key: Key): boolean {
            return this.keyState[key] || false;
        }
        
        // Internal use
        public static _translateKeyCode(keyCode: number): Key {
            return this.keyCodeLookupTable[keyCode] || Key.Unknown;
        }
        
        public static _setKeyState(key: Key, value: boolean): void {
            this.keyState[key] = value;
        }
    }
    
    export enum Key {
        Unknown,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        Escape,
        Control,
        Shift,
        Alt,
        LSystem,
        RSystem,
        Menu,
        LBracket,
        RBracket,
        SemiColon,
        Comma,
        Period,
        Quote,
        Slash,
        BackSlash,
        Grave,
        Equal,
        Dash,
        Space,
        Return,
        BackSpace,
        Tab,
        PageUp,
        PageDown,
        End,
        Home,
        Insert,
        Delete,
        Add,
        Subtract,
        Multiply,
        Divide,
        Left,
        Right,
        Up,
        Down,
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        ScrollLock,
        NumLock,
        CapsLock,
        Pause
    }
}
